
package pojos;

import javax.swing.ImageIcon;//libreria para tratamiento de imagenes en objetos
import javax.swing.JOptionPane;

public class TestMaskotas extends javax.swing.JFrame {

    //variable objeto para llamar una imagen   
    ImageIcon ilogo= new ImageIcon("src/img/maskota.png");
    
    public TestMaskotas() {//inicia construcotr
        initComponents();
        setTitle("Tienda maskotas TOVAR!!!!");
        setLocationRelativeTo(null);//cetra ventana
        
 JOptionPane.showMessageDialog(null, "Bienvenido a sistemas Maskotas","SISTEMA DE CONSULTAS",JOptionPane.PLAIN_MESSAGE,ilogo);
    }//termina constructor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        panSelecciona = new javax.swing.JPanel();
        btnConsulCaninos = new javax.swing.JButton();
        btnCosulGatos = new javax.swing.JButton();
        btnConsulAves = new javax.swing.JButton();
        lblImgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTitulo.setText("Tienda maskotas TOVAR");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        panSelecciona.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Selecciona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        panSelecciona.setOpaque(false);

        btnConsulCaninos.setBackground(new java.awt.Color(255, 255, 255));
        btnConsulCaninos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConsulCaninos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton.png"))); // NOI18N
        btnConsulCaninos.setText("Consultar Caninos");
        btnConsulCaninos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulCaninosActionPerformed(evt);
            }
        });

        btnCosulGatos.setBackground(new java.awt.Color(255, 255, 255));
        btnCosulGatos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCosulGatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton.png"))); // NOI18N
        btnCosulGatos.setText("Consultar Gatos");

        btnConsulAves.setBackground(new java.awt.Color(255, 255, 255));
        btnConsulAves.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnConsulAves.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton.png"))); // NOI18N
        btnConsulAves.setText("Consultar Aves");

        javax.swing.GroupLayout panSeleccionaLayout = new javax.swing.GroupLayout(panSelecciona);
        panSelecciona.setLayout(panSeleccionaLayout);
        panSeleccionaLayout.setHorizontalGroup(
            panSeleccionaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSeleccionaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panSeleccionaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnConsulCaninos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCosulGatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsulAves, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panSeleccionaLayout.setVerticalGroup(
            panSeleccionaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSeleccionaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnConsulCaninos)
                .addGap(18, 18, 18)
                .addComponent(btnCosulGatos)
                .addGap(18, 18, 18)
                .addComponent(btnConsulAves)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        getContentPane().add(panSelecciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 61, -1, -1));

        lblImgFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.png"))); // NOI18N
        getContentPane().add(lblImgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 470, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsulCaninosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulCaninosActionPerformed
        // generacion de objetos caninos
        Canino canino1=new Canino(2, "Firulais", "MiniToy");
               canino1.imprimirDatosCanino();
       Canino canino2=new Canino(1, "Fifi", "Chihuahua");
               canino2.imprimirDatosCanino();        
    }//GEN-LAST:event_btnConsulCaninosActionPerformed

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestMaskotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestMaskotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestMaskotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestMaskotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestMaskotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulAves;
    private javax.swing.JButton btnConsulCaninos;
    private javax.swing.JButton btnCosulGatos;
    private javax.swing.JLabel lblImgFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panSelecciona;
    // End of variables declaration//GEN-END:variables
}
